version: '1'

services:
  mongo:
    image: mongo
    container_name: finance_mdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
    ports:
      - 27018:27017
    volumes:
      - 'finance_mdb:/data/db'
    networks:
      - net

  mongo-express:
    image: mongo-express
    container_name: finance_mde
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_admin
      ME_CONFIG_MONGODB_URL: mongodb://mongo_admin:mongo_admin@mongo:27017/
    depends_on:
      - mongo
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.0
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8083:8000
    networks:
      - net

volumes:
  finance_mdb:
  index_data:
    driver: local

networks:
  net:
    driver: bridge