version: '1'

services:
  mongo:
    image: mongo
    container_name: finance_mdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
    ports:
      - 27018:27017
    volumes:
      - 'finance_mdb:/data/db'

  mongo-express:
    image: mongo-express
    container_name: finance_mde
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_admin
      ME_CONFIG_MONGODB_URL: mongodb://mongo_admin:mongo_admin@mongo:27017/
    depends_on:
      - mongo

volumes:
  finance_mdb: